package com.stockpredictor.app.ui.screens.settings

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import com.stockpredictor.app.ui.components.ClayAppBar
import com.stockpredictor.app.ui.components.ClayCard
import com.stockpredictor.app.ui.theme.ClayColor
import com.stockpredictor.app.ui.theme.ClaySpacing

/**
 * Phase 6 DoD: covers, in plain language, every data category this app actually collects across
 * every phase built so far — checked against CLAUDE.md's phase-by-phase feature list, not
 * boilerplate. Linked from Settings (below); reachable within two taps from every screen a
 * disclaimer also appears on.
 */
private data class PrivacySection(val title: String, val body: String)

private val sections = listOf(
    PrivacySection(
        "Account (Firebase Authentication)",
        "When you sign up or log in, your email address and a securely hashed password are " +
            "stored by Firebase Authentication (Google) to identify your account. We never see or " +
            "store your raw password ourselves.",
    ),
    PrivacySection(
        "Watchlist & portfolio sync (Firestore)",
        "Your watchlist and portfolio holdings are stored locally on this device and synced to " +
            "Firebase Firestore under your account so they carry over to your other signed-in " +
            "devices. This data is not shared with any other user.",
    ),
    PrivacySection(
        "Push notifications (Firebase Cloud Messaging)",
        "A device token is registered with Firebase Cloud Messaging so price-move and prediction " +
            "alerts you configure can be delivered to this device. The token identifies this " +
            "device/app install, not you personally.",
    ),
    PrivacySection(
        "Market data (CoinGecko)",
        "Coin prices, charts, and search results are fetched from CoinGecko. No account or " +
            "personal information is sent as part of these requests.",
    ),
    PrivacySection(
        "AI predictions",
        "Price predictions are generated by our own backend and AI service from public market " +
            "data — no personal data is sent to or used by the prediction model. Predictions are " +
            "informational only and are not investment advice.",
    ),
    PrivacySection(
        "On-device momentum classifier",
        "The on-device momentum feature runs entirely on this device using a local TensorFlow " +
            "Lite model and your cached price history. Nothing is uploaded for this feature — it " +
            "works even in airplane mode.",
    ),
    PrivacySection(
        "\"Ask AI\" chatbot",
        "Messages you send to the chatbot leave this device: they are sent through our backend " +
            "to a third-party AI provider (Google Gemini) to generate a reply, then discarded " +
            "server-side. Conversation history is kept only locally on this device, not on our " +
            "servers.",
    ),
    PrivacySection(
        "Maps",
        "The Exchange Map screen displays static exchange locations using the Google Maps SDK. " +
            "This screen does not access or share your device's location.",
    ),
    PrivacySection(
        "Crash diagnostics (Firebase Crashlytics)",
        "If the app crashes, technical diagnostic information (device model, OS version, and the " +
            "point in the app where the crash occurred) is sent to Firebase Crashlytics to help us " +
            "fix bugs. This does not include your watchlist, portfolio, or chat content.",
    ),
    PrivacySection(
        "Your choices",
        "You can sign out at any time from Settings, which stops any further sync. To request " +
            "deletion of your account and associated cloud data, contact us using the email " +
            "associated with your account.",
    ),
)

@Composable
fun PrivacyPolicyScreen(onBack: () -> Unit) {
    Column(modifier = Modifier.fillMaxSize().background(ClayColor.Background)) {
        ClayAppBar(title = "Privacy Policy", onBack = onBack)
        LazyColumn(
            modifier = Modifier.weight(1f).fillMaxWidth(),
            contentPadding = PaddingValues(ClaySpacing.Lg),
            verticalArrangement = Arrangement.spacedBy(ClaySpacing.Md),
        ) {
            item {
                Text(
                    "This page explains what data AI Crypto Predictor collects and why, in plain " +
                        "language.",
                    color = ClayColor.TextSecondary,
                    style = MaterialTheme.typography.bodyMedium,
                )
            }
            items(sections) { section ->
                ClayCard(modifier = Modifier.fillMaxWidth()) {
                    Column {
                        Text(
                            section.title,
                            color = ClayColor.TextPrimary,
                            style = MaterialTheme.typography.titleMedium,
                            fontWeight = FontWeight.Bold,
                        )
                        Text(
                            section.body,
                            color = ClayColor.TextSecondary,
                            style = MaterialTheme.typography.bodyMedium,
                        )
                    }
                }
            }
        }
    }
}
